// <auto-generated />
using System;
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp1.EditorOptionsBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EditorType");

                    b.Property<bool>("ReadOnly");

                    b.HasKey("Id");

                    b.ToTable("EditorOptionsBase");

                    b.HasDiscriminator<int>("EditorType");
                });

            modelBuilder.Entity("ConsoleApp1.EditorOptionsCalendar", b =>
                {
                    b.HasBaseType("ConsoleApp1.EditorOptionsBase");


                    b.ToTable("EditorOptionsCalendar");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ConsoleApp1.EditorOptionsNumberBox", b =>
                {
                    b.HasBaseType("ConsoleApp1.EditorOptionsBase");

                    b.Property<string>("Format");

                    b.Property<string>("InvalidValueMessage");

                    b.Property<string>("Mask");

                    b.Property<string>("MaskChar");

                    b.Property<string>("MaskInvalidMessage");

                    b.Property<double?>("Max");

                    b.Property<double?>("Min");

                    b.Property<int?>("Mode");

                    b.Property<string>("Placeholder");

                    b.Property<bool>("ShowClearButton");

                    b.Property<int>("ShowMaskMode");

                    b.Property<bool>("ShowSpinButtons");

                    b.Property<bool>("Spellcheck");

                    b.Property<double>("Step");

                    b.Property<bool>("UseLargeSpinButtons");

                    b.ToTable("EditorOptionsNumberBox");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("ConsoleApp1.EditorOptionsTextArea", b =>
                {
                    b.HasBaseType("ConsoleApp1.EditorOptionsBase");

                    b.Property<bool>("AutoResizeEnabled");

                    b.Property<string>("Mask")
                        .HasColumnName("EditorOptionsTextArea_Mask");

                    b.Property<string>("MaskChar")
                        .HasColumnName("EditorOptionsTextArea_MaskChar");

                    b.Property<string>("MaskInvalidMessage")
                        .HasColumnName("EditorOptionsTextArea_MaskInvalidMessage");

                    b.Property<double?>("MaxHeight");

                    b.Property<int?>("MaxLength");

                    b.Property<double?>("MinHeight");

                    b.Property<int?>("Mode")
                        .HasColumnName("EditorOptionsTextArea_Mode");

                    b.Property<string>("Placeholder")
                        .HasColumnName("EditorOptionsTextArea_Placeholder");

                    b.Property<bool>("ShowClearButton")
                        .HasColumnName("EditorOptionsTextArea_ShowClearButton");

                    b.Property<int>("ShowMaskMode")
                        .HasColumnName("EditorOptionsTextArea_ShowMaskMode");

                    b.Property<bool>("Spellcheck")
                        .HasColumnName("EditorOptionsTextArea_Spellcheck");

                    b.ToTable("EditorOptionsTextArea");

                    b.HasDiscriminator().HasValue(14);
                });

            modelBuilder.Entity("ConsoleApp1.EditorOptionsTextBox", b =>
                {
                    b.HasBaseType("ConsoleApp1.EditorOptionsBase");

                    b.Property<string>("Mask")
                        .HasColumnName("EditorOptionsTextBox_Mask");

                    b.Property<string>("MaskChar")
                        .HasColumnName("EditorOptionsTextBox_MaskChar");

                    b.Property<string>("MaskInvalidMessage")
                        .HasColumnName("EditorOptionsTextBox_MaskInvalidMessage");

                    b.Property<int?>("Mode")
                        .HasColumnName("EditorOptionsTextBox_Mode");

                    b.Property<string>("Placeholder")
                        .HasColumnName("EditorOptionsTextBox_Placeholder");

                    b.Property<bool>("ShowClearButton")
                        .HasColumnName("EditorOptionsTextBox_ShowClearButton");

                    b.Property<int>("ShowMaskMode")
                        .HasColumnName("EditorOptionsTextBox_ShowMaskMode");

                    b.Property<bool>("Spellcheck")
                        .HasColumnName("EditorOptionsTextBox_Spellcheck");

                    b.ToTable("EditorOptionsTextBox");

                    b.HasDiscriminator().HasValue(15);
                });
#pragma warning restore 612, 618
        }
    }
}
